version: '3.9'

services:
  web:
    build: .
    container_name: eshop_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-)4oze!1-hfoc#)rma!lr$$58g!3+o!7b5vffy*-u)uxi4u#t2pb"
      - "DJANGO_DEBUG=False"
      - "DJANGO_ALLOWED_HOSTS=['localhost', '127.0.0.1']"
    depends_on:
      - db


  db:
    image: postgres
    container_name: eshop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: